@startuml

package "ch.etmles.payroll" {
    class PayrollApplication {
        +main(String[): void
    }

    "PayrollApplication" --> "SpringApplication"

    package "Department" {
        class "DepartmentController" {
            {static}+ressourceName: String
            +all(): DepartmentEntity[]
            +newEmployee(DepartmentEntity): DepartmentEntity
            +one(Long): DepartmentEntity
            +replaceDepartment(DepartmentEntity, Long): DepartmentEntity
            +deleteDepartment(Long): void
        }

        class "DepartmentEntity"{
            (...)
        }

        interface "DepartmentRepository"<extends JARepository<DepartmentEntity, Long>>

        "DepartmentController" --> "DepartmentRepository"
        "DepartmentController" --> "DepartmentEntity"
    }

    "DepartmentController" --> "Exceptions"

    package "Employee" {
        class "EmployeeController" {
            {static}+ressourceName: String
            +all(): EmployeeEntity[]
            +newEmployee(EmployeeEntity): EmployeeEntity
            +one(Long): EmployeeEntity
            +replaceEmployee(EmployeeEntity, Long): EmployeeEntity
            +deleteEmployee(Long): void
            +joinDepartment(Long, Long): void
            +leaveDepartment(Long): void
        }

        class "EmployeeEntity" {
            (...)
        }

        class "EmployeeAdvice"
        exception "EmployeeNotInDepartment"
        exception "EmployeeAlreadyInDepartment"

        interface "EmployeeRepository"<extends JARepository<EmployeeEntity, Long>>

        "EmployeeController" --> "EmployeeRepository"
        "EmployeeController" --> "EmployeeEntity"
        "EmployeeController" --> "EmployeeNotInDepartment"
        "EmployeeController" --> "EmployeeAlreadyInDepartment"
    }

    "EmployeeController" --> "Exceptions"

    package "Exceptions" {
        exception "ResourceIDNotFound"
        exception "ResourceDeleteNotFound"
        class "ResourceNotFoundAdvice"
    }

    class "LoadDatabase" {
        initEmployees(EmployeeRepository): CommandLineRunner
        initDepartments(DepartmentRepository): CommandLineRunner
    }
}

@enduml