services:
  reverse-proxy:
    container_name: spring-boot-reverse-proxy
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-reverse-proxy.conf:/etc/nginx/nginx.conf

  spring-boot:
    container_name: spring-boot-api
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING.DATASOURCE.URL=jdbc:mysql://mysql:3306/payroll
      - SPRING.DATASOURCE.USERNAME=payroll_connector
      - SPRING.DATASOURCE.PASSWORD=secret
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: spring-boot-mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=payroll
      - MYSQL_USER=payroll_connector
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10